export const GOLF_CLUB_BRANDS = [
	"Acer Golf",
	"Adams Golf",
	"Alien Golf",
	"Ben Hogan Golf",
	"Bettinardi Golf",
	"Bloodline Golf",
	"Bridgestone Golf",
	"Callaway Golf",
	"Cayman Golf",
	"Cleveland Golf",
	"Cobra Golf",
	"Confidence Golf",
	"Continental Golf",
	"Dunlop Sport",
	"Edel Golf",
	"Epon Golf",
	"Evnroll",
	"Fourteen Golf",
	"Founders Club",
	"Hireko Golf",
	"Honma Golf",
	"Kasco Golf",
	"Katana Golf",
	"Krank Golf",
	"KZG (Kenneth Zink Golf)",
	"LAB Golf",
	"Lynx Golf",
	"MacGregor Golf",
	"Maltby Golf",
	"Maruman Golf",
	"Miura Golf",
	"Mizuno",
	"Never Compromise",
	"Nike Golf",
	"Northwestern Golf",
	"Odyssey Golf",
	"PING",
	"Piretti Golf",
	"PRGR",
	"PXG (Parsons Xtreme Golf)",
	"Pinemeadow Golf",
	"Precise Golf",
	"Ram Golf",
	"Rife Putters",
	"Royal Collection",
	"Scotty Cameron",
	"SIK Golf",
	"Slazenger Golf",
	"Snake Eyes Golf",
	"Spalding Golf",
	"Srixon",
	"Sub 70 Golf",
	"TaylorMade",
	"Titleist",
	"Tommy Armour Golf",
	"Top-Flite",
	"Toulon Design",
	"Tour Edge",
	"US Kids Golf",
	"Vice Golf",
	"Warrior Custom Golf",
	"Wilson Golf",
	"Wilson Staff",
	"Wishon Golf",
	"XXIO",
	"Yonex Golf",
] as const;
